version: '2'
services:
    idnest:
        build:
            context: .
            args:
                PORT: "8910"
                WORKERS: "4"
                TIMEOUT: "30"
        ports: 
            - "8910:8910"
        depends_on:
            - redis
        environment:
            - IDNEST_CONFIG=/code/config.py
    redis:
        image: "redis"
        entrypoint: "redis-server --appendonly yes"
